sudo : required
services :
  - docker

before_install :
  - docker build -t mazzama/practice-docker-react -f Dockerfile.dev .

script :
  - docker run mazzama/practice-docker-react npm run test -- --coverage

deploy :
  provider : elasticbeanstalk
  region : "us-east-1"
  app : "docker-app"
  env : "DockerApp-env"
  bucket_name : "elasticbeanstalk-us-east-1-071713164084"
  bucket_path : "docker-app"
  on :
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key :
    secure : "$AWS_SECRET_KEY"